export const queryKeys = {
  campaigns: {
    all: ['campaigns'] as const,
    detail: (id: string) => ['campaigns', id] as const,
    purchases: (id: string) => ['campaigns', id, 'purchases'] as const,
    sales: (id: string) => ['campaigns', id, 'sales'] as const,
    pnl: (id: string) => ['campaigns', id, 'pnl'] as const,
    channelPnl: (id: string) => ['campaigns', id, 'channelPnl'] as const,
    fillRate: (id: string, days: number) => ['campaigns', id, 'fillRate', days] as const,
    daysToSell: (id: string) => ['campaigns', id, 'daysToSell'] as const,
    inventory: (id: string) => ['campaigns', id, 'inventory'] as const,
    tuning: (id: string) => ['campaigns', id, 'tuning'] as const,
    crackCandidates: (id: string) => ['campaigns', id, 'crackCandidates'] as const,
    expectedValues: (id: string) => ['campaigns', id, 'expectedValues'] as const,
    activationChecklist: (id: string) => ['campaigns', id, 'activationChecklist'] as const,
    projections: (id: string) => ['campaigns', id, 'projections'] as const,
  },
  credit: {
    summary: ['credit', 'summary'] as const,
    config: ['credit', 'config'] as const,
    invoices: ['credit', 'invoices'] as const,
  },
  portfolio: {
    health: ['portfolio', 'health'] as const,
    channelVelocity: ['portfolio', 'channelVelocity'] as const,
    insights: ['portfolio', 'insights'] as const,
    suggestions: ['portfolio', 'suggestions'] as const,
    capitalTimeline: ['portfolio', 'capitalTimeline'] as const,
    weeklyReview: ['portfolio', 'weeklyReview'] as const,
    revocations: ['portfolio', 'revocations'] as const,
    sellSheet: ['portfolio', 'sellSheet'] as const,
    globalInventory: ['portfolio', 'globalInventory'] as const,
    sellSheetItems: ['portfolio', 'sellSheetItems'] as const,
  },
  favorites: {
    all: ['favorites'] as const,
    list: (page: number, pageSize: number) => ['favorites', 'list', page, pageSize] as const,
  },
  pricing: {
    sets: ['pricing', 'sets'] as const,
    search: (query: string) => ['pricing', 'search', query] as const,
    cardPrice: (key: string | string[]) => ['pricing', 'card', key] as const,
  },
  admin: {
    allowlist: ['admin', 'allowlist'] as const,
    users: ['admin', 'users'] as const,
    apiUsage: ['admin', 'apiUsage'] as const,
    cacheStats: ['admin', 'cacheStats'] as const,
    cardRequests: ['admin', 'cardRequests'] as const,
    pricingDiagnostics: ['admin', 'pricingDiagnostics'] as const,
    priceOverrideStats: ['admin', 'priceOverrideStats'] as const,
    aiUsage: ['admin', 'aiUsage'] as const,
    priceFlags: (status: string) => ['admin', 'priceFlags', status] as const,
    cardLadderStatus: ['admin', 'cardLadderStatus'] as const,
    marketMoversStatus: ['admin', 'marketMoversStatus'] as const,
    dhStatus: ['admin', 'dhStatus'] as const,
    dhUnmatched: ['admin', 'dhUnmatched'] as const,
    psaSyncStatus: ['admin', 'psaSyncStatus'] as const,
  },
  social: {
    all: ['social'] as const,
    list: () => ['social', 'list'] as const,
    detail: (id: string) => ['social', id] as const,
  },
  instagram: {
    all: ['instagram'] as const,
    status: () => ['instagram', 'status'] as const,
  },
  purchases: {
    psaPendingItems: ['purchases', 'psaPendingItems'] as const,
  },
} as const;
