package azureai

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/guarzo/slabledger/internal/adapters/clients/httpx"
	"github.com/guarzo/slabledger/internal/domain/ai"
	"github.com/guarzo/slabledger/internal/domain/observability"
)

// Config configures the Azure AI Foundry client.
type Config struct {
	Endpoint       string // https://<resource>.openai.azure.com
	APIKey         string // Azure API key
	DeploymentName string // e.g. "gpt-4o"
	APIVersion     string // e.g. "2024-12-01-preview"
}

// Option configures the client.
type Option func(*Client)

// WithLogger sets the logger.
func WithLogger(l observability.Logger) Option {
	return func(c *Client) { c.logger = l }
}

// Client implements ai.LLMProvider for Azure AI Foundry (OpenAI-compatible).
type Client struct {
	config     Config
	httpClient *http.Client
	logger     observability.Logger
}

// NewClient creates a new Azure AI Foundry client.
// This client only supports API-key authentication. For Azure OpenAI endpoints
// (*.openai.azure.com, *.cognitiveservices.azure.com, *.services.ai.azure.com)
// the key is sent via the "api-key" header. Bearer-token (Entra ID / managed
// identity) auth is not supported — use a separate client or extend Config if
// needed.
func NewClient(cfg Config, opts ...Option) (*Client, error) {
	if cfg.Endpoint == "" {
		return nil, fmt.Errorf("azureai: Endpoint is required")
	}
	if cfg.APIKey == "" {
		return nil, fmt.Errorf("azureai: APIKey is required (bearer-token auth is not supported)")
	}
	if cfg.DeploymentName == "" {
		return nil, fmt.Errorf("azureai: DeploymentName is required")
	}
	if cfg.APIVersion == "" {
		cfg.APIVersion = "2024-12-01-preview"
	}

	c := &Client{
		config: cfg,
		// No http.Client.Timeout — it covers the entire response lifetime
		// and would abort long-running SSE streams. Connection-level timeouts
		// are configured on the Transport; stream deadlines come from ctx.
		httpClient: &http.Client{
			Transport: httpx.DefaultTransport(),
		},
	}
	for _, opt := range opts {
		opt(c)
	}
	return c, nil
}

var _ ai.LLMProvider = (*Client)(nil)

// rateLimitError signals a 429 from the API (HTTP or SSE stream).
type rateLimitError struct{ raw string }

func (e *rateLimitError) Error() string {
	return "responses API rate limited: " + e.raw
}

// capacityError signals an Azure "no_capacity" error — the request exceeds the
// maximum usage size allowed during peak load on pay-as-you-go tier.
type capacityError struct{ raw string }

func (e *capacityError) Error() string {
	return "azure ai capacity exceeded: " + e.raw
}

const maxStreamRetries = 5

// StreamCompletion streams a chat completion response from Azure AI.
// Automatically selects the Responses API for AI Foundry endpoints
// and the Chat Completions API for Azure OpenAI endpoints.
// Retries automatically on transient errors (rate limits, connection resets)
// with exponential backoff. For the Responses API, retries are allowed even
// after partial text deltas if response.completed was not received. For the
// Chat Completions API, any emitted chunk prevents retry.
func (c *Client) StreamCompletion(ctx context.Context, req ai.CompletionRequest, stream func(ai.CompletionChunk)) error {
	responsesAPI := c.useResponsesAPI()
	var lastErr error
	var lastResponseID string
	for attempt := range maxStreamRetries {
		emitted := false
		completed := false
		wrappedStream := func(chunk ai.CompletionChunk) {
			emitted = true
			if chunk.Done {
				completed = true
			}
			stream(chunk)
		}
		var respID string
		respID, lastErr = c.doStreamCompletion(ctx, req, wrappedStream)
		if respID != "" {
			lastResponseID = respID
		}
		if lastErr == nil {
			return nil
		}
		// Decide whether retry is safe:
		// - Responses API: retry unless Done was emitted. Intermediate text
		//   deltas will be regenerated by the server (previous_response_id
		//   chaining replays the full response). Note: the caller may receive
		//   duplicate deltas from the failed attempt; this is an acceptable
		//   tradeoff vs permanent failure. The scheduler path uses a no-op
		//   stream callback, so duplicates only affect fullContent accumulation.
		// - Chat Completions: any emitted chunk is final; retrying would
		//   duplicate streamed content.
		noRetry := completed || (!responsesAPI && emitted)
		if noRetry || attempt == maxStreamRetries-1 {
			break
		}
		// Don't retry permanent client errors (4xx except 429).
		if isPermanentError(lastErr) {
			break
		}
		// If we captured a response ID and store is enabled, skip further
		// retries and go straight to poll fallback to avoid duplicate POSTs.
		if lastResponseID != "" && req.Store && responsesAPI {
			goto pollFallback
		}
		// Capacity errors need the longest backoff (request too large for peak load).
		// Rate limits need moderate backoff; other transient errors use shorter.
		var capErr *capacityError
		var rlErr *rateLimitError
		var backoff time.Duration
		if errors.As(lastErr, &capErr) {
			backoff = time.Duration(60<<attempt) * time.Second // 60s, 120s, 240s
		} else if errors.As(lastErr, &rlErr) {
			backoff = time.Duration(30<<attempt) * time.Second // 30s, 60s, 120s
		} else {
			backoff = time.Duration(5<<attempt) * time.Second // 5s, 10s, 20s
		}
		if c.logger != nil {
			c.logger.Warn(ctx, "retrying after transient error",
				observability.Int("attempt", attempt+1),
				observability.Int("backoffSec", int(backoff.Seconds())),
				observability.Err(lastErr),
			)
		}
		select {
		case <-ctx.Done():
			lastErr = ctx.Err()
			goto pollFallback
		case <-time.After(backoff):
		}
	}

pollFallback:
	// Poll-based fallback: if streaming failed but we captured a response ID
	// and the request used store=true, the response may have completed server-side.
	// Try to retrieve it via GET /responses/{id}.
	if lastResponseID != "" && req.Store && responsesAPI {
		// Use a fresh context for the poll — the original may be deadline-exceeded,
		// but the response may still have completed server-side.
		pollCtx, pollCancel := context.WithTimeout(context.Background(), 3*time.Minute)
		defer pollCancel()
		if c.logger != nil {
			c.logger.Info(pollCtx, "attempting poll fallback for stored response",
				observability.String("responseID", lastResponseID))
		}
		if pollErr := c.pollResponseFallback(pollCtx, lastResponseID, stream); pollErr == nil {
			return nil
		} else {
			if c.logger != nil {
				c.logger.Warn(pollCtx, "poll fallback failed", observability.Err(pollErr))
			}
			return pollErr
		}
	}

	return lastErr
}

// pollResponseFallback retrieves a stored response via GET when streaming failed.
// It polls up to 10 times (10s apart, with a 20s initial wait to let Azure finish processing).
// Total budget: ~110s, fitting within the 3-minute poll context.
func (c *Client) pollResponseFallback(ctx context.Context, responseID string, stream func(ai.CompletionChunk)) error {
	endpoint := strings.TrimRight(c.config.Endpoint, "/")
	var url string
	if strings.Contains(endpoint, ".services.ai.azure.com") {
		url = endpoint + "/openai/v1/responses/" + responseID
	} else {
		url = fmt.Sprintf("%s/openai/deployments/%s/responses/%s?api-version=%s",
			endpoint, c.config.DeploymentName, responseID, responsesAPIVersion)
	}

	for poll := range 10 {
		// Wait before each poll — give Azure time to finish processing.
		wait := 10 * time.Second
		if poll == 0 {
			wait = 20 * time.Second // longer initial wait
		}
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-time.After(wait):
		}

		httpReq, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
		if err != nil {
			return err
		}
		// Use the same auth method as streaming requests.
		if isAzureOpenAI(endpoint) {
			httpReq.Header.Set("api-key", c.config.APIKey)
		} else {
			httpReq.Header.Set("Authorization", "Bearer "+c.config.APIKey)
		}

		resp, err := c.httpClient.Do(httpReq)
		if err != nil {
			return err
		}
		body, _ := io.ReadAll(resp.Body)
		resp.Body.Close() //nolint:errcheck

		if resp.StatusCode == http.StatusNotFound {
			// Response not stored yet — keep polling.
			if c.logger != nil {
				c.logger.Info(ctx, "poll fallback: response not found yet, will retry",
					observability.Int("poll", poll+1))
			}
			continue
		}
		if resp.StatusCode != http.StatusOK {
			return fmt.Errorf("poll response returned %d", resp.StatusCode)
		}

		var result struct {
			ID     string `json:"id"`
			Status string `json:"status"`
			Output []struct {
				Type    string `json:"type"`
				Content []struct {
					Type string `json:"type"`
					Text string `json:"text"`
				} `json:"content"`
				Name      string `json:"name"`
				CallID    string `json:"call_id"`
				Arguments string `json:"arguments"`
			} `json:"output"`
			Usage struct {
				InputTokens  int `json:"input_tokens"`
				OutputTokens int `json:"output_tokens"`
				TotalTokens  int `json:"total_tokens"`
			} `json:"usage"`
			IncompleteDetails *struct {
				Reason string `json:"reason"`
			} `json:"incomplete_details"`
		}
		if err := json.Unmarshal(body, &result); err != nil {
			return fmt.Errorf("parse poll response: %w", err)
		}

		switch result.Status {
		case "completed", "incomplete":
			if result.Status == "incomplete" {
				reason := "unknown"
				if result.IncompleteDetails != nil && result.IncompleteDetails.Reason != "" {
					reason = result.IncompleteDetails.Reason
				}
				if c.logger != nil {
					c.logger.Warn(ctx, "poll fallback: response incomplete, emitting partial output",
						observability.String("responseID", responseID),
						observability.String("reason", reason),
						observability.Int("outputItems", len(result.Output)),
					)
				}
			}
			// Emit the response as chunks. For "incomplete" responses
			// (typically max_output_tokens), the partial output is still
			// useful — a truncated analysis is better than no analysis.
			chunk := ai.CompletionChunk{
				Done:              true,
				ConversationState: result.ID,
			}
			if result.Usage.TotalTokens > 0 {
				chunk.Usage = &ai.TokenUsage{
					InputTokens:  result.Usage.InputTokens,
					OutputTokens: result.Usage.OutputTokens,
					TotalTokens:  result.Usage.TotalTokens,
				}
			}
			for _, out := range result.Output {
				switch out.Type {
				case "message":
					for _, c := range out.Content {
						if c.Type == "output_text" && c.Text != "" {
							chunk.Delta += c.Text
						}
					}
				case "function_call":
					chunk.ToolCalls = append(chunk.ToolCalls, ai.ToolCall{
						ID:        out.CallID,
						Name:      out.Name,
						Arguments: out.Arguments,
					})
				}
			}
			stream(chunk)
			return nil
		case "failed", "cancelled":
			return fmt.Errorf("response %s: status %s", responseID, result.Status)
		default:
			// "queued", "in_progress" — keep polling
			if c.logger != nil {
				c.logger.Info(ctx, "poll fallback waiting",
					observability.String("status", result.Status),
					observability.Int("poll", poll+1))
			}
		}
	}
	return fmt.Errorf("response %s still not completed after polling", responseID)
}
